language: python

# Mention the python version in which travis will run the app
python:
  - "3.7"


# command to install dependencies in the requirements file
# You can also install the coverage here to avoid it being in the requirements file
# It is important to avoid things like coverage, pep8 that are not required to run the app

  

# command to run tests 
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
install:
    - pip install pipenv
  
deploy:
  provider: Heroku 
  skip-cleanup: true
  github-token: $GITHUB_TOKEN   
  app: CramSchoolApp
  repo: LiaozhiCheng/CramSchoolApp
  target_branch: main
script:
    - npm run test