language: python

# Mention the python version in which travis will run the app
python:
  - "3.7"


# command to install dependencies in the requirements file
# You can also install the coverage here to avoid it being in the requirements file
# It is important to avoid things like coverage, pep8 that are not required to run the app

  

# command to run tests 
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
script: true
  - nosetests --with-coverage --coverage report
  
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  skip_cleanup: true
  
  app: CramSchoolApp
  on:
    repo: LiaozhiCheng/CramSchoolApp
    branch: master